accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.generic.base import TemplateView

# Django는 elegant URL을 지원!
# 정규표현식(regular expression)

urlpatterns = [
    url(r"^$", TemplateView.as_view(template_name='index.html')),
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls'))
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('list/', views.p_list, name='list'),
    path('create/', views.p_create, name='create'),
    path('<int:post_id>/delete/', views.p_delete, name='delete'),
    path('<int:post_id>/update/', views.p_update, name='update'),
    path('<int:post_id>/read/', views.p_read, name='read'),
    path('<int:comments_id>/c_delete/', views.c_delete, name='c_delete'),
    # path('<int:comments_id>/c_create/', views.c_create, name='c_create')

]

accounts/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):

    auth_author = models.ForeignKey(User, on_delete=models.CASCADE)
    author = models.CharField('작성자', max_length=20)
    title = models.CharField('제목', max_length=30, default="")
    contents = models.TextField('글내용', max_length=1000)
    # CharField는 한 둘, TextField는 여러 줄

    def __str__(self):
        return self.contents

class Comments(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comments_text = models.TextField('댓글 내용', max_length=1000)
    comments_author = models.CharField('작성자', max_length=20, default="")

    def __str__(self):
        return  self.comments_text

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "email")

posts/forms.py
from django import forms
from posts.models import Post
from posts.models import Comments

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'contents']     # 자동으로 input할 컬럼명

class CommentsForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ['comments_author', 'comments_text']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from accounts.forms import UserForm
# from django.contrib import auth

def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('accounts:login')
    else:
        form = UserForm()
    return render(request, 'accounts/signup.html', {'form': form})

# def signup(request):
#     pass
#     if request.method == "POST":
#         if request.POST["password1"] == request.POST['password2']:
#             user = User.object.creat_user(
#                 username=request.POST["username"], password=request.POST['password1'])
#             auth.login(request, user)
#             return redirect('home')
#         return render(request, 'signup.html')
#     return render(request, 'signup.html')


# def login(request):
#     if request.method == "POST":
#         username = request.POST['username']
#         password = request.POST['password']
#         user = auth.authenticate(request, username=username, password=password)
#         if user is not None:
#             auth.login(request, user)
#             return redirect('home')
#         else:
#             return render(request, 'login.html', {'error': 'username of password is incorrect'})
#     else:
#         return render(request, 'login.html')
#
#
# def logout(request):
#     auth.logout(request)
#     return redirect('home')
# #

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from posts.models import Post, Comments
from posts.forms import PostForm, CommentsForm


def p_list(request):
    my_list = Post.objects.all().order_by('-id')
    context = {'posts': my_list}
    return render(request, 'list.html', context)


def p_create(request):

    if request.method == 'POST':  # POST 방식으로 호출될 때
        post_form = PostForm(request.POST)

        if post_form.is_valid():
            post = post_form.save(commit=False)
            post.auth_author = request.user
            post.save()
            return redirect('posts:list')

    else:         # GET 방식으로 호출될 때
        post_form = PostForm()

    return render(request, 'create.html', {'post_form': post_form})

 # form외에는 다 get방식이라고 보면 됨/


def p_delete(request, post_id):
    post = Post.objects.get(id=post_id)   # id대신 pk로 해도 됨
    post.delete()

    return redirect('posts:list')


def p_update(request, post_id):
    post = get_object_or_404(Post, pk=post_id)

    if request.method == 'POST':
        post_form = PostForm(request.POST, instance=post)

        if post_form.is_valid():
            post_form.save()
            return redirect('posts:list')

    else:
        post_form = PostForm(instance=post)

    return render(request, 'create.html', {'post_form': post_form})

def p_read(request, post_id):

    post = Post.objects.get(id=post_id)
    comments = post.comments_set.all()              ## 여기서 계속 애먹었었음

    if request.method == 'POST':  # POST 방식으로 호출될 때
        comments_form = CommentsForm(request.POST)
        if comments_form.is_valid():
            com = comments_form.save(commit=False)
            com.post_id = post.pk
            com.save()
            return redirect('posts:read', post_id=post.pk)

    else:
        comments_form = CommentsForm()

    context = {"post": post,
               "comments": comments,
               "Comments_Form": comments_form}

    return render(request, 'contents.html', context)




def c_delete(request, comments_id):
    comments = Comments.objects.get(id=comments_id)
    comments.delete()

    return redirect('posts:read', post_id=comments.post_id)

accounts/templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

accounts/templates/login.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block content %}
<div class="container my-3">

    <form method="post" class="post-form" action="{% url 'account:login' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
{% endblock %}

accounts/templates/signup.html
2221231231231

blog/templates/accounts/login.html
{% extends 'base.html' %}

{% block container %}
<div class="container my-3">
    <div class="row">
        <div class="col-4">
            <h4>로그인</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'accounts:signup' %}">계정을 만드세요.</a></span>
        </div>
    </div>
    <form method="post" class="post-form" action="{% url 'accounts:login' %}">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">  <!-- 로그인 성공후 이동되는 URL -->
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
{% endblock %}

blog/templates/accounts/signup.html
{% extends 'base.html' %}

{% block container %}

<div class="container my-3">
    <div class="row my-3">
        <div class="col-4">
            <h4>계정생성</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'accounts:login' %}">로그인 하세요.</a></span>
        </div>
    </div>
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자 이름</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
</div>

{% endblock %}

blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/css/bootstrap.min.css" integrity="sha384-VCmXjywReHh4PwowAiWNagnWcLhlEJLA5buUprzK8rxFgeH0kww/aWY76TfkUoSX" crossorigin="anonymous">
</head>
<body>
    {% block container %}
    {% endblock %}
</body>
</html>

blog/templates/index.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Blog System</title>

    <!-- Bootstrap core CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/css/bootstrap.min.css" integrity="sha384-VCmXjywReHh4PwowAiWNagnWcLhlEJLA5buUprzK8rxFgeH0kww/aWY76TfkUoSX" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="/static/css/cover.css" rel="stylesheet">
  </head>

  <body class="text-center">
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header class="masthead mb-auto">
    <div class="inner">
      <h3 class="masthead-brand">My Blog</h3>

    </div>
  </header>

  <main role="main" class="inner cover">
    <h1 class="cover-heading">Welcome to my blog.</h1>
    <p class="lead">powered by bootstrap.</p>
    <p class="lead">
      <a href="/posts/list/" class="btn btn-lg btn-secondary">Enter BBS</a>
    </p>
  </main>

  <footer class="mastfoot mt-auto">
    <div class="inner">
      <p>Cover template for <a href="https://getbootstrap.com/">Bootstrap</a>, by <a href="https://twitter.com/mdo">@mdo</a>.</p>
    </div>
  </footer>
</div>
</body>
</html>

posts/templates/contents.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block container %}

    <div class="container">
        <h1>{{ post.title }}</h1>
        <h4>{{ post.contents }}</h4>
    </div>
<br><br>
    <div class="container">
        <h2>댓글</h2>


        <div class="m-1">

            <table class="table table-hover">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">작성자</th>
                        <th scope="col">내용</th>
                        <th scope="col">삭제</th>
                    </tr>
                </thead>
                <tbody>
                {% for comments in comments %}
                 <tr>
                     <td>{{ comments.comments_author }}</td>
                     <td>{{ comments.comments_text }}</td>
                     <td>
                         <a href="{% url 'posts:c_delete' comments.id %}" class="btn btn-danger">삭제</a>
                     </td>
                 </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

        <form action="{% url 'posts:read' post.id %}" method="post">
            {% csrf_token %}
            {% bootstrap_form Comments_Form %}
            <button type="submit" class="btn btn-dark">등록</button>
        </form>
        <br>
          <a href="/posts/list/" class="btn btn-light">게시판으로 돌아가기</a>

    </div>
{% endblock %}

posts/templates/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block container %}

    <div class="container">
        <h1>새글 작성</h1>

        <form method="post">
            {% csrf_token %}
            {% bootstrap_form post_form %}
            <button type="submit" class="btn btn-primary">등록</button>
        </form>

    </div>
{% endblock %}

posts/templates/list.html
{% extends 'base.html' %}
{% block container %}
    <script src="/static/js/posts.js"></script>
    <div class="container">
        <h1>Bulletin Board System(BBS)</h1>


{% if user.is_authenticated %}
         <button class="btn btn-primary btn-sm"
                 onclick="new_post()">새글 작성</button>
        <a href="{% url 'accounts:logout' %}" class="btn btn-outline-info btn-sm float-right">{{ user.username }} (LOGOUT)</a>
        {% else %}
        <button class="btn btn-primary btn-sm">새글 작성</button> (로그인 필요)
        <a href="{% url 'accounts:login' %}" class="btn btn-outline-info btn-sm float-right">LOGIN</a>
{% endif %}

        <div class="m-1">

            <table class="table table-hover">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">작성자</th>
                        <th scope="col">제목</th>
                        <th scope="col">수정</th>
                        <th scope="col">삭제</th>
                    </tr>
                </thead>
                <tbody>
                    {% for post in posts %}

                    <tr>
                        <th scope="row">{{ post.id }}</th>
                        <td>{{ post.auth_author.username }}</td>
                        <td>
                            <a href="{% url 'posts:read' post.id %}">{{ post.title }}</a>
                        </td>
                        <td>
                            <a href="{% url 'posts:update' post.id %}" class="btn btn-warning btn-sm">수정</a>
                        </td>
                        <td>
                            <a href="{% url 'posts:delete' post.id %}" class="btn btn-danger btn-sm">삭제</a>
                        </td>
                    </tr>

                {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
{% endblock %}